FROM nginx:stable-alpine

RUN apk update \
    && apk add --no-cache \
    bash \
    inotify-tools 

# Prepare cleanuping - Create dirs and remove files
RUN rm -rf /usr/share/nginx/html \
    && rm -rf /etc/nginx/nginx.conf

# Update config - Linking new files as configurations
RUN ln -sf /usr/share/nginx/nginx.conf /etc/nginx/nginx.conf \
    && ln -sf /dev/stdout /var/log/nginx/default.stdout.access.log

ENV PATH=$PATH:/usr/local/bin/scripts \
    MODE=Developement

CMD ["bash", "-c", ". checkMode.sh && run-nginx.sh"]
