FROM jenkins:latest
MAINTAINER Pascal Kern pascal.kern@gmail.com


# Enable/install root access with sudo
USER root
RUN apt-get update \
      && apt-get install -y sudo \
      && rm -rf /var/lib/apt/lists/*
RUN echo "jenkins ALL=NOPASSWD: ALL" >> /etc/sudoers
USER jenkins



# Used for applications/servlets inside a tomcat instance! (See: https://ptmccarthy.github.io/2014/07/24/remote-jmx-with-docker/)
# ENV CATALINA_OPTS="-Xdebug -Xrunjdwp:transport=dt_socket,server=y,address=62911,suspend=n \
# -Dcom.sun.management.jmxremote=\
# -Dcom.sun.management.jmxremote.port=1898 \
# -Dcom.sun.management.jmxremote.ssl=false \
# -Dcom.sun.management.jmxremote.authenticate=false \
# -Djava.rmi.server.hostname=192.168.99.100" # <- IP of docker-machine ip <machine>

## To be tested with the ${} inside the ENV declaration! Else use bellow version but what
## hapens with CATALINA_OPTS inside the image?! They should not be overwritten!
# ENV CATALINA_OPTS="${CATALINA_OPTS} -Xdebug -X...."


