version: '3.0'

services:
  jenkins:
    build: .
    environemnt:
      JAVA_OPTS: "-Djava.awt.headles=true"
      # JENKINS_OPTS: 
      # JENKINS_SLAVE_AGENT_PORT: 
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      # - /var/jenkins_home # Already done in base Dockerfile from hub